import { Jeu } from './jeu';

export const JEUX: Jeu[] = [
  { id: 1, name: 'CS:GO', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter',img:'csgo', url:"test" },
  { id: 2, name: 'Rainbow Six: Siege', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter',img:'r6', url:"test" },
  { id: 3, name: 'StarWars Battlefront II', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter', img:'sw2', url:"test" },
  { id: 4, name: 'Red Dead Redemption 2', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter', img:'rdr2', url:"test" },
  { id: 5, name: 'Fortnite', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter', img:'fortnite', url:"test" },
  { id: 6, name: 'CS:GO', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu..',note:'Vous devez vous connecter',img:'csgo', url:"test" },
  { id: 7, name: 'Rainbow Six: Siege', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter',img:'r6', url:"test" },
  { id: 8, name: 'StarWars Battlefront II', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter', img:'sw2', url:"test" },
  { id: 9, name: 'Red Dead Redemption 2', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter', img:'rdr2', url:"test" },
  { id: 10, name: 'Fortnite', summary:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis volutpat tellus ut iaculis. Suspendisse porta ullamcorper orci, sit amet vestibulum nunc tempus convallis. Phasellus ut ornare arcu.',note:'Vous devez vous connecter', img:'fortnite', url:"test" }
];